# Generated by Django 5.0.14 on 2026-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
