# Generated by Django 5.0.14 on 2026-03-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_user_notes_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('RESET_PASSWORD', 'Đặt lại mật khẩu'), ('STATUS_CHANGE', 'Đổi trạng thái'), ('RESCHEDULE', 'Đổi lịch hẹn'), ('CREATE_ACCOUNT', 'Tạo tài khoản')], max_length=32)),
                ('resource_type', models.CharField(help_text='e.g. Specialty, Doctor, Receptionist, Appointment, User', max_length=32)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('resource_label', models.CharField(blank=True, help_text='Human-readable resource name, e.g. "BS. Nguyễn Văn A"', max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='portal_admi_action_73f1ef_idx'), models.Index(fields=['resource_type'], name='portal_admi_resourc_8af27b_idx'), models.Index(fields=['actor_role'], name='portal_admi_actor_r_73a4da_idx'), models.Index(fields=['-created_at'], name='portal_admi_created_6f4f8d_idx')],
            },
        ),
    ]
