# Generated by Django 5.0.14 on 2026-04-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_hash_patient_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='account_password',
            field=models.CharField(max_length=128),
        ),
    ]
