# Generated by Django 5.0.14 on 2026-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_patientprofile_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='auth_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
