# Generated by Django 5.0.14 on 2026-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_patientprofile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='otp_reset_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='otp_reset_token',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
