# Generated by Django 5.0.14 on 2026-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_add_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='otp_reset_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='otp_reset_token',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
