[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test
testpaths = appointments catalog portal
norecursedirs = .
python_files = tests.py test_*.py tests_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --tb=short
    -q
markers =
    slow: marks tests as slow
    integration: marks tests as integration tests
