# Generated by Django 5.0.14 on 2026-03-14 15:28

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['-scheduled_start', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
