# Generated by Django 5.0.14 on 2026-03-15 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_appointment_managers'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('VISIT_15', 'Khám 15 phút'), ('VISIT_20', 'Khám 20 phút'), ('VISIT_40', 'Khám 40 phút')], default='VISIT_20', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('block_index', models.PositiveSmallIntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupied_blocks', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_blocks', to='catalog.doctor')),
            ],
            options={
                'ordering': ['appointment_date', 'block_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentblock',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'block_index'), name='uniq_appointment_block_per_doctor'),
        ),
    ]
