# Generated by Django 5.0.14 on 2026-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_visit_type_appointmentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('VISIT_15', 'Khám 15 phút'), ('VISIT_20', 'Khám 20 phút'), ('VISIT_40', 'Khám 40 phút')], default='VISIT_20', max_length=20),
        ),
    ]
