# Generated by Django 5.0.14 on 2026-03-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_visit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('CONFIRM', 'Xác nhận'), ('CANCEL', 'Hủy lịch'), ('CHECKIN', 'Check-in'), ('NO_SHOW', 'No-show'), ('RESCHEDULE', 'Dời lịch'), ('COMPLETE', 'Hoàn tất khám'), ('DELETE', 'Xóa')], max_length=20)),
                ('changed_by', models.CharField(blank=True, help_text='Tên người thực hiện (staff name hoặc "Hệ thống")', max_length=150)),
                ('changed_by_role', models.CharField(blank=True, help_text='Vai trò: admin / receptionist / doctor', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Ghi chú bổ sung (vd: lý do hủy, lịch cũ → lịch mới)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Appointment History',
                'verbose_name_plural': 'Appointment Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
