# Generated by Django 5.0.14 on 2026-04-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenthistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Tạo mới'), ('CONFIRM', 'Xác nhận'), ('CANCEL', 'Hủy lịch'), ('CHECKIN', 'Check-in'), ('MOVE_TO_DOCTOR', 'Chuyển sang bác sĩ'), ('NO_SHOW', 'No-show'), ('RESCHEDULE', 'Dời lịch'), ('COMPLETE', 'Hoàn tất khám'), ('DELETE', 'Xóa')], max_length=20),
        ),
    ]
