# Generated by Django 5.0.14 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointmenthistory_action'),
    ]

    operations = [
        # Composite indexes for common query patterns
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['status', '-scheduled_start'],
                name='apt_status_date_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['doctor', 'scheduled_start'],
                name='apt_doctor_date_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['patient_phone', '-scheduled_start'],
                name='apt_patient_phone_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['is_deleted', 'status'],
                name='apt_deleted_status_idx',
            ),
        ),
        # Index on AppointmentHistory for audit queries
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(
                fields=['appointment', '-created_at'],
                name='hist_apt_date_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='appointmenthistory',
            index=models.Index(
                fields=['changed_by_role', '-created_at'],
                name='hist_role_date_idx',
            ),
        ),
    ]
