from django.urls import path

from .views import (
    AdminAuditLogsAPIView,
    AdminReportsAPIView,
    CurrentPatientAccountAPIView,
    CurrentPatientProfileAPIView,
    DoctorQueueAPIView,
    DoctorScheduleAPIView,
    DoctorVisitCompleteAPIView,
    DoctorVisitDetailAPIView,
    DoctorVisitDraftAPIView,
    DoctorVisitsAPIView,
    PatientAppointmentsAPIView,
    PatientChangePasswordAPIView,
    PatientClaimProfileAPIView,
    PatientNotificationDetailAPIView,
    PatientNotificationsAPIView,
    PatientNotificationsMarkAllReadAPIView,
    PatientRecordDetailAPIView,
    PatientRegisterAPIView,
    ReceptionPatientsAPIView,
    LoginAPIView,
    PatientVerifyOTPAPIView, 
)

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view(), name='auth-login'),
    path('patient/auth/register/', PatientRegisterAPIView.as_view(), name='patient-auth-register'),
    path('patient/profile/', CurrentPatientProfileAPIView.as_view(), name='patient-profile'),
    path('patient/account/', CurrentPatientAccountAPIView.as_view(), name='patient-account'),
    path('patient/change-password/', PatientChangePasswordAPIView.as_view(), name='patient-change-password'),
    path('patient/appointments/', PatientAppointmentsAPIView.as_view(), name='patient-appointments'),
    path('patient/records/<str:record_code>/', PatientRecordDetailAPIView.as_view(), name='patient-record-detail'),
    path('patient/claim-profile/', PatientClaimProfileAPIView.as_view(), name='patient-claim-profile'),
    path('patient/notifications/', PatientNotificationsAPIView.as_view(), name='patient-notifications'),
    path('patient/notifications/mark-all-read/', PatientNotificationsMarkAllReadAPIView.as_view(), name='patient-notifications-mark-all'),
    path('patient/notifications/<int:notification_id>/', PatientNotificationDetailAPIView.as_view(), name='patient-notification-detail'),
    path('doctor/schedule/', DoctorScheduleAPIView.as_view(), name='doctor-schedule'),
    path('doctor/queue/', DoctorQueueAPIView.as_view(), name='doctor-queue'),
    path('doctor/visits/', DoctorVisitsAPIView.as_view(), name='doctor-visits'),
    path('doctor/visits/<str:code>/', DoctorVisitDetailAPIView.as_view(), name='doctor-visit-detail'),
    path('doctor/visits/<str:code>/draft/', DoctorVisitDraftAPIView.as_view(), name='doctor-visit-draft'),
    path('doctor/visits/<str:code>/complete/', DoctorVisitCompleteAPIView.as_view(), name='doctor-visit-complete'),
    path('reception/patients/', ReceptionPatientsAPIView.as_view(), name='reception-patients'),
    path('admin/audit-logs/', AdminAuditLogsAPIView.as_view(), name='admin-audit-logs'),
    path('admin/reports/', AdminReportsAPIView.as_view(), name='admin-reports'),
    path('patient/auth/verify-otp/', PatientVerifyOTPAPIView.as_view(), name='patient-verify-otp'),
]
