from django.urls import path

from .views import (
    AdminAuditLogsAPIView,
    AdminDashboardAPIView,
    AdminDoctorDetailAPIView,
    AdminPatientProfileAPIView,
    AdminPatientProfileResetPasswordAPIView,
    AdminPatientProfilesAPIView,
    AdminReceptionistProfileAPIView,
    AdminReceptionistProfileResetPasswordAPIView,
    AdminReceptionistProfilesAPIView,
    AdminReportsAPIView,
    CurrentPatientAccountAPIView,
    CurrentPatientProfileAPIView,
    DoctorChangePasswordAPIView,
    DoctorQueueAPIView,
    DoctorScheduleAPIView,
    DoctorVisitCompleteAPIView,
    DoctorVisitDetailAPIView,
    DoctorVisitDraftAPIView,
    DoctorVisitStartAPIView,
    DoctorVisitsAPIView,
    DoctorProfileAPIView,
    LogoutAPIView,
    PatientAppointmentsAPIView,
    PatientChangePasswordAPIView,
    PatientClaimProfileAPIView,
    PatientNotificationDetailAPIView,
    PatientNotificationsAPIView,
    PatientNotificationsMarkAllReadAPIView,
    PatientRecordDetailAPIView,
    PatientRegisterAPIView,
    ReceptionChangePasswordAPIView,
    ReceptionDashboardAPIView,
    ReceptionPatientsAPIView,
    ReceptionProfileAPIView,
    LoginAPIView,
)

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view(), name='auth-login'),
    path('auth/logout/', LogoutAPIView.as_view(), name='auth-logout'),
    path('patient/auth/register/', PatientRegisterAPIView.as_view(), name='patient-auth-register'),
    path('patient/profile/', CurrentPatientProfileAPIView.as_view(), name='patient-profile'),
    path('patient/account/', CurrentPatientAccountAPIView.as_view(), name='patient-account'),
    path('patient/change-password/', PatientChangePasswordAPIView.as_view(), name='patient-change-password'),
    path('patient/appointments/', PatientAppointmentsAPIView.as_view(), name='patient-appointments'),
    path('patient/records/<str:record_code>/', PatientRecordDetailAPIView.as_view(), name='patient-record-detail'),
    path('patient/claim-profile/', PatientClaimProfileAPIView.as_view(), name='patient-claim-profile'),
    path('patient/notifications/', PatientNotificationsAPIView.as_view(), name='patient-notifications'),
    path('patient/notifications/mark-all-read/', PatientNotificationsMarkAllReadAPIView.as_view(), name='patient-notifications-mark-all'),
    path('patient/notifications/<int:notification_id>/', PatientNotificationDetailAPIView.as_view(), name='patient-notification-detail'),
    path('doctor/schedule/', DoctorScheduleAPIView.as_view(), name='doctor-schedule'),
    path('doctor/queue/', DoctorQueueAPIView.as_view(), name='doctor-queue'),
    path('doctor/visits/', DoctorVisitsAPIView.as_view(), name='doctor-visits'),
    path('doctor/visits/<str:code>/', DoctorVisitDetailAPIView.as_view(), name='doctor-visit-detail'),
    path('doctor/visits/<str:code>/start/', DoctorVisitStartAPIView.as_view(), name='doctor-visit-start'),
    path('doctor/visits/<str:code>/draft/', DoctorVisitDraftAPIView.as_view(), name='doctor-visit-draft'),
    path('doctor/visits/<str:code>/complete/', DoctorVisitCompleteAPIView.as_view(), name='doctor-visit-complete'),
    path('doctor/profile/', DoctorProfileAPIView.as_view(), name='doctor-profile'),
    path('doctor/change-password/', DoctorChangePasswordAPIView.as_view(), name='doctor-change-password'),
    path('reception/patients/', ReceptionPatientsAPIView.as_view(), name='reception-patients'),
    path('reception/dashboard/', ReceptionDashboardAPIView.as_view(), name='reception-dashboard'),
    path('reception/profile/', ReceptionProfileAPIView.as_view(), name='reception-profile'),
    path('reception/change-password/', ReceptionChangePasswordAPIView.as_view(), name='reception-change-password'),
    path('admin/audit-logs/', AdminAuditLogsAPIView.as_view(), name='admin-audit-logs'),
    path('admin/reports/', AdminReportsAPIView.as_view(), name='admin-reports'),
    path('admin/dashboard/', AdminDashboardAPIView.as_view(), name='admin-dashboard'),
    path('admin/doctor-detail/<int:doctor_id>/', AdminDoctorDetailAPIView.as_view(), name='admin-doctor-detail'),
    path('admin/patient-profiles/', AdminPatientProfilesAPIView.as_view(), name='admin-patient-profiles'),
    path('admin/patient-profiles/<int:profile_id>/', AdminPatientProfileAPIView.as_view(), name='admin-patient-profile'),
    path('admin/patient-profiles/<int:profile_id>/reset-password/', AdminPatientProfileResetPasswordAPIView.as_view(), name='admin-patient-profile-reset-password'),
    path('admin/receptionist-profiles/', AdminReceptionistProfilesAPIView.as_view(), name='admin-receptionist-profiles'),
    path('admin/receptionist-profiles/<int:profile_id>/', AdminReceptionistProfileAPIView.as_view(), name='admin-receptionist-profile'),
    path('admin/receptionist-profiles/<int:profile_id>/reset-password/', AdminReceptionistProfileResetPasswordAPIView.as_view(), name='admin-receptionist-profile-reset-password'),
]
